[default]
extend-ignore-re = [
  "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
]

[default.extend-words]
# Add project-specific words here
edn = "edn"
GTI = "GTI"
GTIDs = "GTIDs"
BRIN = "BRIN"
RTO = "RTO"
AKS = "AKS"
Hashi = "Hashi"
strat = "strat"
ND = "ND"
Ba = "Ba"
fpr = "fpr"
ttest = "ttest"
hve = "hve"
EXAT = "EXAT"
PXAT = "PXAT"
DOUB = "DOUB"
FLOA = "FLOA"
INSER = "INSER"
INSERTs = "INSERTs"
