[default]
extend-ignore-re = [
  "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
]

[default.extend-words]
# Add project-specific words here
GTI = "GTI"
GTIDs = "GTIDs"
BRIN = "BRIN"
RTO = "RTO"
AKS = "AKS"
Hashi = "Hashi"
strat = "strat"
ND = "ND"
Ba = "Ba"
